services:
  backend:
    build: ./truck_backend
    ports:
      - "3333:3333"
    env_file:
      - ./truck_backend/.env.prod   # สำหรับ prod
    depends_on:
      - mssql

  frontend:
    build: ./frontend-one
    ports:
      - "3001:3000"
    depends_on:
      - backend
      