version: '3.9'

services:
  backend:
    build: ./truck_backend
    ports:
      - "3333:3333"
    env_file:
      - ./truck_backend/.env.prod
    depends_on:
      - mssql

  frontend:
    build: ./frontend-one
    ports:
      - "3001:3001"
    depends_on:
      - backend

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest   # เปลี่ยนเป็น 2019-latest ถ้าใช้ Docker Official
    container_name: mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=isylzjko@1234
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data:
