name: CI-CD Pipeline

on:
  push:
    branches:
      - main   # ทำงานเมื่อ push เข้า main
  pull_request:
    branches:
      - main   # ทำงานเมื่อมีการเปิด PR เข้า main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build-test   # ✅ จะรัน deploy ได้ก็ต่อเมื่อ test ผ่าน
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Server
        run: |
          echo "🚀 Deploying to server..."
          # เช่น ใช้ rsync หรือ scp copy ไฟล์ไปยัง server
          # rsync -avz ./ user@your-server:/var/www/app
